# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: java_build
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=kunal-tech_DevSecops_Pipeline -Dsonar.organization=kunal-tech -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=e8232e8085d7856b699504d5d08195c7b5f4ca9e
